name: CI

on:
  schedule:
    - cron: 0 0 * * * # daily

  workflow_dispatch:

jobs:
  push:
    name: make app.db & push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '102.0.5005.61'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: chrome --version

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 16

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: mv chromedriver
        run: sudo mv /usr/local/bin/chromedriver ./chromedriver.exe

      - name: Execute Gradle run
        run: ./gradlew run

      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'database'
          destination-github-username: 'cbnuEarthProtector'
          destination-repository-name: 'atto'
          user-email: chisan2001@gmail.com
          target-branch: db-update
          target-directory: 'app/src/main/assets/database'
